export enum UserRole {
  CUSTOMER       = 'ROLE_CUSTOMER',
  SURVEYOR       = 'ROLE_SURVEYOR',
  ADJUSTOR       = 'ROLE_ADJUSTOR',
  CASE_MANAGER   = 'ROLE_CASE_MANAGER',
  AUDITOR        = 'ROLE_AUDITOR',
  WORKSHOP       = 'ROLE_WORKSHOP',
  REGIONAL_MGR   = 'ROLE_REGIONAL_MGR',
  TOP_MANAGEMENT = 'ROLE_TOP_MANAGEMENT',
}

export const INTERNAL_ROLES: UserRole[] = [
  UserRole.SURVEYOR, UserRole.ADJUSTOR, UserRole.CASE_MANAGER,
  UserRole.AUDITOR, UserRole.REGIONAL_MGR, UserRole.TOP_MANAGEMENT,
];
